use std::collections::BTreeMap;
use std::net::{IpAddr, Ipv4Addr};

use serde::{Deserialize, Serialize};

use crate::crdt::hlc::HLC;
use crate::crdt::merge::MergeResult;

/// A DHCP lease entry in the mesh CRDT.
///
/// Keyed by MAC address at `/devices/{mac}`. One entry per device.
/// Uses `IpAddr` (v4/v6 enum) for forward compatibility with IPv6.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LeaseEntry {
    pub mac: [u8; 6],
    /// IPv4 today; IPv6 forward-compatible without schema change.
    pub ip: IpAddr,
    pub hostname: Option<String>,
    pub router_id: String,
    /// Unix timestamp in seconds; daemon reaps expired entries.
    pub expiry: u64,
    pub hlc: HLC,
}

/// MAC → lease. Key is [`mac_key`].
pub type LeaseBook = BTreeMap<String, LeaseEntry>;

/// Lowercase `aa:bb:cc:dd:ee:ff`.
pub fn mac_key(mac: &[u8; 6]) -> String {
    format!(
        "{:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
        mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]
    )
}

/// Parse `aa:bb:cc:dd:ee:ff` or `aa-bb-cc-dd-ee-ff`.
pub fn parse_mac(s: &str) -> Option<[u8; 6]> {
    let hex: String = s.chars().filter(|c| c.is_ascii_hexdigit()).collect();
    if hex.len() != 12 {
        return None;
    }
    let mut mac = [0u8; 6];
    for (i, chunk) in hex.as_bytes().chunks(2).enumerate() {
        mac[i] = u8::from_str_radix(std::str::from_utf8(chunk).ok()?, 16).ok()?;
    }
    Some(mac)
}

/// `10.42.x.y` → `10.42.x.1`. Other v4 is None (do not invent a gw).
pub fn gateway_v4(ip: Ipv4Addr) -> Option<Ipv4Addr> {
    let o = ip.octets();
    if o[0] == 10 && o[1] == 42 {
        Some(Ipv4Addr::new(10, 42, o[2], 1))
    } else {
        None
    }
}

/// Merge one MAC's lease. Last-writer-wins on HLC: the latest ACK is the
/// address other APs must OFFER (keep-current, not first-ever).
pub fn merge_lease(local: Option<&LeaseEntry>, incoming: &LeaseEntry) -> MergeResult<LeaseEntry> {
    match local {
        None => MergeResult::Inserted,
        Some(existing) => match incoming.hlc.cmp(&existing.hlc) {
            std::cmp::Ordering::Greater => MergeResult::Updated,
            _ => MergeResult::Unchanged,
        },
    }
}

/// Apply `incoming` into `book`. Conflict winner is stored (first IP kept).
pub fn apply_lease(book: &mut LeaseBook, incoming: LeaseEntry) -> MergeResult<LeaseEntry> {
    let key = mac_key(&incoming.mac);
    let result = merge_lease(book.get(&key), &incoming);
    match &result {
        MergeResult::Inserted | MergeResult::Updated => {
            book.insert(key, incoming);
        }
        MergeResult::Unchanged | MergeResult::Conflict { .. } => {}
    }
    result
}

/// dnsmasq `dhcp-hostsfile` lines: `mac,ip`.
pub fn render_hostsfile(book: &LeaseBook) -> String {
    let mut lines: Vec<String> = book
        .values()
        .filter_map(|e| {
            let IpAddr::V4(ip) = e.ip else {
                return None;
            };
            Some(format!("{},{}", mac_key(&e.mac), ip))
        })
        .collect();
    lines.sort();
    lines.push(String::new());
    lines.join("\n")
}

/// Extra dnsmasq config: offer the CRDT IP with that /24's `.1` as router.
pub fn render_roam_conf(book: &LeaseBook) -> String {
    let mut lines = vec![
        "# generated by mjolnir-meshd — CRDT DHCP roam (wvg.4)".to_string(),
    ];
    let mut tags: Vec<(u8, Ipv4Addr)> = Vec::new();
    for e in book.values() {
        let IpAddr::V4(ip) = e.ip else {
            continue;
        };
        let Some(gw) = gateway_v4(ip) else {
            continue;
        };
        let tag = format!("g{}", ip.octets()[2]);
        lines.push(format!(
            "dhcp-host={},{},set:{}",
            mac_key(&e.mac),
            ip,
            tag
        ));
        let octet = ip.octets()[2];
        if !tags.iter().any(|(o, _)| *o == octet) {
            tags.push((octet, gw));
        }
    }
    tags.sort_by_key(|(o, _)| *o);
    for (octet, gw) in tags {
        lines.push(format!(
            "dhcp-option=tag:g{octet},option:router,{gw}"
        ));
        lines.push(format!(
            "dhcp-option=tag:g{octet},option:netmask,255.255.255.0"
        ));
    }
    lines.push(String::new());
    lines.join("\n")
}

/// Drop leases whose `expiry` is at or before `now_unix`. Returns the removed
/// keys so the caller can gossip `LeaseRelease`.
pub fn reap_expired(book: &mut LeaseBook, now_unix: u64) -> Vec<LeaseEntry> {
    let mut gone = Vec::new();
    book.retain(|_, e| {
        if e.expiry <= now_unix {
            gone.push(e.clone());
            false
        } else {
            true
        }
    });
    gone
}

#[cfg(test)]
mod tests {
    use std::net::IpAddr;
    use std::net::Ipv4Addr;

    use super::*;
    use crate::crdt::merge::MergeResult;

    fn hlc(wall: u64, node: &str) -> HLC {
        HLC {
            wall_clock: wall,
            counter: 0,
            node_id: node.to_string(),
        }
    }

    fn lease(mac: [u8; 6], ip: &str, router: &str, wall: u64) -> LeaseEntry {
        LeaseEntry {
            mac,
            ip: IpAddr::V4(ip.parse().unwrap()),
            hostname: None,
            router_id: router.to_string(),
            expiry: 1_700_000_000,
            hlc: hlc(wall, router),
        }
    }

    #[test]
    fn postcard_roundtrip() {
        let original = LeaseEntry {
            mac: [0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF],
            ip: IpAddr::V4(Ipv4Addr::new(192, 168, 1, 42)),
            hostname: Some("laptop".to_string()),
            router_id: "router-a".to_string(),
            expiry: 1_700_000_000,
            hlc: HLC {
                wall_clock: 1_700_000_000_000,
                counter: 0,
                node_id: "router-a".to_string(),
            },
        };
        let bytes = postcard::to_allocvec(&original).unwrap();
        let decoded: LeaseEntry = postcard::from_bytes(&bytes).unwrap();
        assert_eq!(original, decoded);
    }

    #[test]
    fn parse_mac_colon_or_dash() {
        let want = [0xde, 0x45, 0x53, 0xf5, 0xf7, 0x74];
        assert_eq!(parse_mac("de:45:53:f5:f7:74"), Some(want));
        assert_eq!(parse_mac("DE-45-53-F5-F7-74"), Some(want));
        assert_eq!(mac_key(&want), "de:45:53:f5:f7:74");
    }

    #[test]
    fn gateway_is_slash24_dot1_in_mesh_space() {
        assert_eq!(
            gateway_v4("10.42.203.146".parse().unwrap()),
            Some("10.42.203.1".parse().unwrap())
        );
        assert_eq!(gateway_v4("192.168.1.42".parse().unwrap()), None);
    }

    #[test]
    fn latest_ack_wins_even_when_the_ip_changed() {
        let mac = [0xde, 0x45, 0x53, 0xf5, 0xf7, 0x74];
        let home = lease(mac, "10.42.242.243", "wr3000s-a", 100);
        let current = lease(mac, "10.42.203.246", "indoor-c", 200);
        let mut book = LeaseBook::new();
        assert!(matches!(apply_lease(&mut book, home), MergeResult::Inserted));
        assert!(matches!(
            apply_lease(&mut book, current),
            MergeResult::Updated
        ));
        assert_eq!(
            book[&mac_key(&mac)].ip,
            "10.42.203.246".parse::<IpAddr>().unwrap()
        );
    }

    #[test]
    fn stale_ack_does_not_roll_the_ip_back() {
        let mac = [0xde, 0x45, 0x53, 0xf5, 0xf7, 0x74];
        let mut book = LeaseBook::new();
        apply_lease(&mut book, lease(mac, "10.42.203.246", "indoor-c", 200));
        apply_lease(&mut book, lease(mac, "10.42.242.243", "wr3000s-a", 100));
        assert_eq!(
            book[&mac_key(&mac)].ip,
            "10.42.203.246".parse::<IpAddr>().unwrap()
        );
    }

    #[test]
    fn reap_expired_drops_only_old_rows() {
        let mut book = LeaseBook::new();
        let mut live = lease([1u8; 6], "10.42.1.10", "a", 1);
        live.expiry = 200;
        let mut dead = lease([2u8; 6], "10.42.1.11", "a", 1);
        dead.expiry = 50;
        apply_lease(&mut book, live);
        apply_lease(&mut book, dead);
        let gone = reap_expired(&mut book, 100);
        assert_eq!(gone.len(), 1);
        assert_eq!(book.len(), 1);
    }

    #[test]
    fn same_ip_updates_router_on_newer_hlc() {
        let mac = [1u8; 6];
        let a = lease(mac, "10.42.203.146", "indoor-c", 100);
        let b = lease(mac, "10.42.203.146", "wr3000s-a", 200);
        let mut book = LeaseBook::new();
        apply_lease(&mut book, a);
        assert!(matches!(
            apply_lease(&mut book, b),
            MergeResult::Updated
        ));
        assert_eq!(book[&mac_key(&mac)].router_id, "wr3000s-a");
    }

    #[test]
    fn hostsfile_and_roam_conf_name_the_home_gateway() {
        let mac = [0xde, 0x45, 0x53, 0xf5, 0xf7, 0x74];
        let mut book = LeaseBook::new();
        apply_lease(&mut book, lease(mac, "10.42.203.146", "indoor-c", 1));
        let hosts = render_hostsfile(&book);
        assert!(hosts.contains("de:45:53:f5:f7:74,10.42.203.146"));
        let conf = render_roam_conf(&book);
        assert!(conf.contains("dhcp-host=de:45:53:f5:f7:74,10.42.203.146,set:g203"));
        assert!(conf.contains("dhcp-option=tag:g203,option:router,10.42.203.1"));
    }
}
